### ISSUE TITLE
 'DegreeView' object has no attribute 'items'

### ISSUE THREAD

**Issue by yunanwubei** [sangyh/minimum-vertex-cover#1]
请问一下，这个错误怎么修改
No of nodes in G: 34
No of Edges in G: 78
Initial UpperBound: 34
Traceback (most recent call last):
  File "D:\Pycharm\project_all\mvc_create\min_bnb\minimum-vertex-cover-master\BnB_edited.py", line 306, in <module>
    main(graph_file, output_dir, cutoff, randSeed)
  File "D:\Pycharm\project_all\mvc_create\min_bnb\minimum-vertex-cover-master\BnB_edited.py", line 267, in main
    Sol_VC,times = BnB(g, cutoff)
  File "D:\Pycharm\project_all\mvc_create\min_bnb\minimum-vertex-cover-master\BnB_edited.py", line 111, in BnB
    v = find_maxdeg(CurG)
  File "D:\Pycharm\project_all\mvc_create\min_bnb\minimum-vertex-cover-master\BnB_edited.py", line 218, in find_maxdeg
    deglist_sorted = sorted(deglist.items(), reverse=True, key=operator.itemgetter(
AttributeError: 'DegreeView' object has no attribute 'items'

**Comment by yunanwubei** [comment]
解决了，找到find_maxdeg函数，将整个函数进行 替换
def find_maxdeg(g):
    deglist = dict(g.degree())
    deglist_sorted = sorted(deglist.items(), reverse=True, key=operator.itemgetter(1))
    v = deglist_sorted[0]
    return v
